title: "Zenn CLIで本を作る方法"
summary: "Zenn CLIが提供されているため，GithubでZennの記事や本をすべて管理することが出来る．しかし，Zenn CLIで本を作る方法についてはあまり説明されていない．今回はZenn CLIでbookを作る方法を紹介する．"
topics: ["book", "zenn", "有料本","how2"] # トピック（5つまで）
published: true # falseだと下書き
price: 200 # 有料の場合200〜5000
chapters:
  - introduction # チャプター1
  - results # チャプター2
  - conclusion # チャプター3