title: "zenn cliで本を作る方法"
summary: "zenn cliが提供されているため，githubでzennの記事や本をすべて管理することが出来る．しかし，zenn cliで本を作る方法についてはあまり説明されていない．今回はzenn cliでbookを作る方法を紹介する．"
topics: ["markdown", "zenn", "react"] # トピック（5つまで）
published: true # falseだと下書き
price: 200 # 有料の場合200〜5000
chapters:
  - introduction # チャプター1
  - results # チャプター2
  - conclusion # チャプター3